on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest          # NOTE: both orka-actions-up and orka-actions-down run on `ubuntu-latest`
    steps:
    - name: Job 1
      id: job1
      uses: jeff-vincent/orka-actions-up@org
      with:
        orkaUser: ${{ secrets.ORKA_USER }}
        orkaPass: ${{ secrets.ORKA_PASS }}
        orkaBaseImage: gha-org-agent.img
        githubPat: ${{ secrets.GH_PAT }}
        githubOrg: 'example-org-1'
        vpnUser: ${{ secrets.VPN_USER }}
        vpnPassword: ${{ secrets.VPN_PASSWORD }}
        vpnAddress: ${{ secrets.VPN_ADDRESS }}
        vpnServerCert: ${{ secrets.VPN_SERVER_CERT }}
        vcpuCount: 3
        coreCount: 3
    outputs:
      vm-name: ${{ steps.job1.outputs.vm-name }}
         
  job2:            # NOTE: this is where your macOS-based, GitHub Actions workflow will be executed.
    needs: job1     
    runs-on: [self-hosted, "${{ needs.job1.outputs.vm-name }}"]     # NOTE: this section of the workflow can contain any number of seperate jobs,
    steps:                                                          # but each must have this `runs-on` value.
    - name: Job 2
      id: job2
      run: |
        sw_vers
        
        
        
#   job3:
#     if: always()
#     needs: [job1, job2]               # NOTE: all jobs you wish to run on the macOS instance, 
#     runs-on: ubuntu-latest            # along with the `orka-actions-up` job, must be listed here.
#     steps:
#     - name: Job 3
#       id: job3
#       uses: jeff-vincent/orka-actions-down@v1.1.0
#       with:
#         orkaUser: ${{ secrets.ORKA_USER }}
#         orkaPass: ${{ secrets.ORKA_PASS }}
#         githubPat: ${{ secrets.GH_PAT }}
#         vpnUser: ${{ secrets.VPN_USER }}
#         vpnPassword: ${{ secrets.VPN_PASSWORD }}
#         vpnAddress: ${{ secrets.VPN_ADDRESS }}
#         vpnServerCert: ${{ secrets.VPN_SERVER_CERT }}
#         vmName: ${{ needs.job1.outputs.vm-name }}


